spring:
  jpa:
    hibernate:
      ddl-auto: none
  show-sql: true
  datasource:
    url: jdbc:postgresql://localhost/shopkitting
    username: postgres
    password: 123
  flyway:
    baseline-on-migrate: true